---
language: java

dist: xenial

os: linux

jdk:
- openjdk8
branches:
  except:
  - gh-pages

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
    - MVN_ARGS="--settings build/.travis.settings.xml"

stages:
  - name: Build-Test
  - name: Semantic-Release
  - name: Publish-Release

before_install:
  - sudo apt-get update
  - env | grep TRAVIS
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

jobs:
  include:
    - stage: Semantic-Release
      install:
        - sudo apt-get update
        - sudo apt-get install python
        - nvm install 12
        - npm install -g npm@6.x
        - pip install --user bump2version
        - npm install @semantic-release/changelog
        - npm install @semantic-release/exec
        - npm install @semantic-release/git
        - npm install @semantic-release/github
      script:
        - npx semantic-release
      after_success:
        - echo "Semantic release has successfully created a new tagged-release"

    - jdk: openjdk8
      name: Publish-To-Maven-Central
      install: true
      script:
        - sh build/setupSigning.sh
        - sh build/setMavenVersion.sh
        - mvn deploy $MVN_ARGS -DskipTests -P central
      after_success:
        - echo "Maven artifacts successfully published to Maven Central!"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: target/site/apidocs
